auto/auto-web/src/main/java/com/mycompany/cdi/AutoBean.java
package com.mycompany.cdi;

import com.mycompany.entity.TAuto;
import com.mycompany.faces.IAuto;
import java.io.Serializable;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.validator.ValidatorException;
import javax.inject.Named;


/**
 *
 * @author defender
 */
@Named(value = "autoBean")
@SessionScoped
public class AutoBean  implements Serializable {
    private static final String TABLE = "autoTable";
    private static final String CARD = "autoCard";

    private List<TAuto> items;
    private TAuto selectedItem;
    private String selectedBody;    
    private String selectedEngine;    
    private String selectedTransmission;    
    
    @EJB
    private IAuto autoFacade;    

    public AutoBean() {
    }
    
    @PostConstruct
    void init() {
        refresh();
    }
    
    public String refresh() {
        setItems(autoFacade.findAll());
        return null;
    }

    public String addItem() {
        selectedItem = new TAuto();
        return CARD;
    }

    public String editItem(TAuto auto) {
        selectedItem = auto;
        setSelectedBody(Integer.toString(auto.getIdBody()));
        setSelectedEngine(Integer.toString(auto.getIdEngine()));
        setSelectedTransmission(Integer.toString(auto.getIdTransmission()));
        return CARD;
    }

    public String deleteItem(TAuto auto) {
        items.remove(auto);
        autoFacade.remove(auto);
        return null;
    }
    
    public String saveItem() throws Exception {
        selectedItem.setIdBody(Integer.parseInt(selectedBody));
        selectedItem.setIdEngine(Integer.parseInt(selectedEngine));
        selectedItem.setIdTransmission(Integer.parseInt(selectedTransmission));
        if (items.indexOf(selectedItem) != -1) {
            autoFacade.edit(selectedItem);
        } else {            
            items.add(selectedItem);
            autoFacade.create(selectedItem);
        }
        refresh();
        setSelectedBody(null);
        setSelectedEngine(null);
        setSelectedTransmission(null);
        return TABLE;
    }    
   
    public String cancelItem() {
        setSelectedBody(null);
        setSelectedEngine(null);
        setSelectedTransmission(null);
        return TABLE;
    }    
    
    public List<TAuto> getItems() {
        return items;
    }
        
    private void setItems(List<TAuto> items) {
        this.items = items;        
    }

    public TAuto getSelectedItem() {
        return selectedItem;
    }

    public String getSelectedBody() {
        return selectedBody;
    }

    public void setSelectedBody(String selectedBody) {
        this.selectedBody = selectedBody;
    }

    public String getSelectedEngine() {
        return selectedEngine;
    }

    public void setSelectedEngine(String selectedEngine) {
        this.selectedEngine = selectedEngine;
    }

    public String getSelectedTransmission() {
        return selectedTransmission;
    }

    public void setSelectedTransmission(String selectedTransmission) {
        this.selectedTransmission = selectedTransmission;
    }            
}

auto/auto-web/src/main/java/com/mycompany/cdi/BodyBean.java
package com.mycompany.cdi;

import com.mycompany.entity.TBody;
import com.mycompany.faces.IBody;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.model.SelectItem;
import javax.inject.Named;


/**
 *
 * @author defender
 */
@Named(value = "bodyBean")
@SessionScoped
public class BodyBean  implements Serializable {
    private static final String TABLE = "bodyTable";
    private static final String CARD = "bodyCard";

    private List<TBody> items;
    private TBody selectedItem;
    private String selectedBodyType;    
    private String selectedColor;    
    
    @EJB
    private IBody bodyFacade;    

    public BodyBean() {
    }
    
    @PostConstruct
    void init() {
        refresh();
    }
    
    public String refresh() {
        setItems(bodyFacade.findAll());        
        return null;
    }       

    public String addItem() {
        selectedItem = new TBody();
        return CARD;
    }

    public String editItem(TBody body) {
        selectedItem = body;
        setSelectedBodyType(Integer.toString(body.getIdBodyType()));
        setSelectedColor(Integer.toString(body.getIdColor()));
        return CARD;
    }

    public String deleteItem(TBody body) {
        items.remove(body);
        bodyFacade.remove(body);
        return null;
    }
    
    public String saveItem() {
        selectedItem.setIdBodyType(Integer.parseInt(selectedBodyType));
        selectedItem.setIdColor(Integer.parseInt(selectedColor));
        if (items.indexOf(selectedItem) != -1) {
            bodyFacade.edit(selectedItem);
        } else {            
            items.add(selectedItem);
            bodyFacade.create(selectedItem);
        }
        refresh();
        setSelectedBodyType(null);
        setSelectedColor(null);
        return TABLE;
    }    
    
    public String cancelItem() {
        setSelectedBodyType(null);
        setSelectedColor(null);
        return TABLE;
    }    
    
    public List<TBody> getItems() {
        return items;
    }
        
    private void setItems(List<TBody> items) {
        this.items = items;        
    }

    public TBody getSelectedItem() {
        return selectedItem;
    }  

    public String getSelectedBodyType() {
        return selectedBodyType;
    }

    public void setSelectedBodyType(String selectedBodyType) {
        this.selectedBodyType = selectedBodyType;
    }        

    public String getSelectedColor() {
        return selectedColor;
    }

    public void setSelectedColor(String selectedColor) {
        this.selectedColor = selectedColor;
    }
    
    public List<SelectItem> getBodyes() {
        List<SelectItem> res = new ArrayList<>();
        for (TBody body : getItems()) {
            res.add(new SelectItem(body.getId(), body.getVin()));
        }
        return res;
    }     
}

auto/auto-web/src/main/java/com/mycompany/cdi/EngineBean.java
package com.mycompany.cdi;

import com.mycompany.entity.TEngine;
import com.mycompany.faces.IEngine;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.model.SelectItem;
import javax.inject.Named;


/**
 *
 * @author defender
 */
@Named(value = "engineBean")
@SessionScoped
public class EngineBean  implements Serializable {
    private static final String TABLE = "engineTable";
    private static final String CARD = "engineCard";

    private List<TEngine> items;
    private TEngine selectedItem;
    private String selectedEngineType;    
    
    @EJB
    private IEngine engineFacade;    

    public EngineBean() {
    }
    
    @PostConstruct
    void init() {
        refresh();
    }
    
    public String refresh() {
        setItems(engineFacade.findAll());
        return null;
    }

    public String addItem() {
        selectedItem = new TEngine();
        return CARD;
    }

    public String editItem(TEngine engine) {
        selectedItem = engine;
        setSelectedEngineType(Integer.toString(engine.getIdEngineType()));
        return CARD;
    }

    public String deleteItem(TEngine engine) {
        items.remove(engine);
        engineFacade.remove(engine);
        return null;
    }
    
    public String saveItem() {
        selectedItem.setIdEngineType(Integer.parseInt(selectedEngineType));
        if (items.indexOf(selectedItem) != -1) {
            engineFacade.edit(selectedItem);
        } else {            
            items.add(selectedItem);
            engineFacade.create(selectedItem);
        }
        refresh();
        setSelectedEngineType(null);
        return TABLE;
    }    
    
    public String cancelItem() {
        setSelectedEngineType(null);
        return TABLE;
    }    
    
    public List<TEngine> getItems() {
        return items;
    }
        
    private void setItems(List<TEngine> items) {
        this.items = items;        
    }

    public TEngine getSelectedItem() {
        return selectedItem;
    }  

    public String getSelectedEngineType() {
        return selectedEngineType;
    }

    public void setSelectedEngineType(String selectedEngineType) {
        this.selectedEngineType = selectedEngineType;
    } 
    
    public List<SelectItem> getEngines() {
        List<SelectItem> res = new ArrayList<>();
        refresh();
        for (TEngine engine : getItems()) {
            res.add(new SelectItem(engine.getId(), engine.getSn()));
        }
        return res;
    }         
}

auto/auto-web/src/main/java/com/mycompany/cdi/EngineTypeBean.java
package com.mycompany.cdi;

import com.mycompany.entity.TEngineType;
import com.mycompany.faces.IEngineType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.model.SelectItem;
import javax.inject.Named;


/**
 *
 * @author defender
 */
@Named(value = "engineTypeBean")
@SessionScoped
public class EngineTypeBean  implements Serializable {
    private static final String TABLE = "engineTypeTable";
    private static final String CARD = "engineTypeCard";

    private List<TEngineType> items;
    private TEngineType selectedItem;
    
    @EJB
    private IEngineType engineTypeFacade;    

    public EngineTypeBean() {
    }
    
    @PostConstruct
    void init() {
        refresh();
    }
    
    public String refresh() {
        setItems(engineTypeFacade.findAll());
        return null;
    }

    public String addItem() {
        selectedItem = new TEngineType();
        return CARD;
    }

    public String editItem(TEngineType engineType) {
        selectedItem = engineType;
        return CARD;
    }

    public String deleteItem(TEngineType engineType) {
        items.remove(engineType);
        engineTypeFacade.remove(engineType);
        return null;
    }
    
    public String saveItem() {
        if (items.indexOf(selectedItem) != -1) {
            engineTypeFacade.edit(selectedItem);
        } else {
            items.add(selectedItem);
            engineTypeFacade.create(selectedItem);
        }
        refresh();
        return TABLE;
    }    
    
    public String cancelItem() {
        return TABLE;
    }    
    
    public List<TEngineType> getItems() {
        return items;
    }
        
    private void setItems(List<TEngineType> items) {
        this.items = items;        
    }

    public TEngineType getSelectedItem() {
        return selectedItem;
    }
    public List<SelectItem> getEngineTypes() {
        List<SelectItem> res = new ArrayList<>();
        refresh();
        for (TEngineType engineType : getItems()) {
            res.add(new SelectItem(engineType.getId(), engineType.getName()));
        }
        return res;
    }          
    
}

auto/auto-web/src/main/java/com/mycompany/cdi/TransmissionBean.java
package com.mycompany.cdi;

import com.mycompany.entity.TTransmission;
import com.mycompany.faces.ITransmission;
import com.mycompany.faces.ITransmissionType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.model.SelectItem;
import javax.inject.Named;


/**
 *
 * @author defender
 */
@Named(value = "transmissionBean")
@SessionScoped
public class TransmissionBean  implements Serializable {
    private static final String TABLE = "transmissionTable";
    private static final String CARD = "transmissionCard";

    private List<TTransmission> items;
    private TTransmission selectedItem;
    private String selectedTransmissionType;    
    
    @EJB
    private ITransmission transmissionFacade;    

    public TransmissionBean() {
    }
    
    @PostConstruct
    void init() {
        refresh();
    }
    
    public String refresh() {
        setItems(transmissionFacade.findAll());
        return null;
    }

    public String addItem() {
        selectedItem = new TTransmission();
        return CARD;
    }

    public String editItem(TTransmission transmission) {
        selectedItem = transmission;
        setSelectedTransmissionType(Integer.toString(transmission.getIdTransmissionType()));
        return CARD;
    }

    public String deleteItem(TTransmission transmission) {
        items.remove(transmission);
        transmissionFacade.remove(transmission);
        return null;
    }
    
    public String saveItem() {
        selectedItem.setIdTransmissionType(Integer.parseInt(selectedTransmissionType));
        if (items.indexOf(selectedItem) != -1) {
            transmissionFacade.edit(selectedItem);
        } else {            
            items.add(selectedItem);
            transmissionFacade.create(selectedItem);
        }
        refresh();
        setSelectedTransmissionType(null);
        return TABLE;
    }    
    
    public String cancelItem() {
        setSelectedTransmissionType(null);
        return TABLE;
    }    
    
    public List<TTransmission> getItems() {
        return items;
    }
        
    private void setItems(List<TTransmission> items) {
        this.items = items;        
    }

    public TTransmission getSelectedItem() {
        return selectedItem;
    }  

    public String getSelectedTransmissionType() {
        return selectedTransmissionType;
    }

    public void setSelectedTransmissionType(String selectedTransmissionType) {
        this.selectedTransmissionType = selectedTransmissionType;
    }    

    public List<SelectItem> getTransmissions() {
        List<SelectItem> res = new ArrayList<>();
        refresh();
        for (TTransmission transmission : getItems()) {
            res.add(new SelectItem(transmission.getId(), transmission.getSn()));
        }
        return res;
    }     
    
}

auto/auto-web/src/main/java/com/mycompany/cdi/TransmissionTypeBean.java
package com.mycompany.cdi;

import com.mycompany.entity.TTransmissionType;
import com.mycompany.faces.ITransmissionType;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.model.SelectItem;
import javax.inject.Named;


/**
 *
 * @author defender
 */
@Named(value = "transmissionTypeBean")
@SessionScoped
public class TransmissionTypeBean  implements Serializable {
    private static final String TABLE = "transmissionTypeTable";
    private static final String CARD = "transmissionTypeCard";

    private List<TTransmissionType> items;
    private TTransmissionType selectedItem;
    
    @EJB
    private ITransmissionType transmissionTypeFacade;    

    public TransmissionTypeBean() {
    }
    
    @PostConstruct
    void init() {
        refresh();
    }
    
    public String refresh() {
        setItems(transmissionTypeFacade.findAll());
        return null;
    }

    public String addItem() {
        selectedItem = new TTransmissionType();
        return CARD;
    }

    public String editItem(TTransmissionType transmissionType) {
        selectedItem = transmissionType;
        return CARD;
    }

    public String deleteItem(TTransmissionType transmissionType) {
        items.remove(transmissionType);
        transmissionTypeFacade.remove(transmissionType);
        return null;
    }
    
    public String saveItem() {
        if (items.indexOf(selectedItem) != -1) {
            transmissionTypeFacade.edit(selectedItem);
        } else {
            items.add(selectedItem);
            transmissionTypeFacade.create(selectedItem);
        }
        refresh();
        return TABLE;
    }    
    
    public String cancelItem() {
        return TABLE;
    }    
    
    public List<TTransmissionType> getItems() {
        return items;
    }
        
    private void setItems(List<TTransmissionType> items) {
        this.items = items;        
    }

    public TTransmissionType getSelectedItem() {
        return selectedItem;
    } 
    
    public List<SelectItem> getTransmissionTypes() {
        List<SelectItem> res = new ArrayList<>();
        refresh();
        for (TTransmissionType transmissionType : getItems()) {
            res.add(new SelectItem(transmissionType.getId(), transmissionType.getName()));
        }
        return res;
    }          
}

auto/auto-web/src/main/webapp/autoCard.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Автомобиль</title>
    </h:head>
    <h:body>        
        <h:form>
            <h:panelGrid columns="2" border="1" cellpadding="10" cellspacing="1">                
                <f:facet name="header">
                    <h:outputText value="Карточка авто"/>
                </f:facet>        
                <h:outputText value="№"/>
                <h:outputText value="#{autoBean.selectedItem.id}"/>                
                <h:outputText value="Кузов"/>
                <h:selectOneMenu value="#{autoBean.selectedBody}" 
                                 validator="#{validatorBean.checkAvailableBody}">                   
                    <f:selectItems value="#{bodyBean.bodyes}"/>                
                </h:selectOneMenu>
                <h:outputText value="Двигатель"/>
                <h:selectOneMenu value="#{autoBean.selectedEngine}"
                                 validator="#{validatorBean.checkAvailableEngine}">
                    <f:selectItems value="#{engineBean.engines}"/>                
                </h:selectOneMenu>          
                <h:outputText value="Трансмиссия"/>
                <h:selectOneMenu value="#{autoBean.selectedTransmission}"
                                 validator="#{validatorBean.checkAvailableTransmission}">
                    <f:selectItems value="#{transmissionBean.transmissions}"/>                
                </h:selectOneMenu>          
                <f:facet name="footer">
                    <h:commandButton value="Сохранить" action="#{autoBean.saveItem()}"/>
                    <h:commandButton value="Закрыть" action="#{autoBean.cancelItem()}">
                        <f:ajax />
                    </h:commandButton>
                </f:facet>                            
            </h:panelGrid>            
        </h:form>
    </h:body>
</html>

auto/auto-web/src/main/webapp/bodyTable.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Таблица кузовов</title>
    </h:head>
    <h:body>        
        <h:form>            
            <h:dataTable value="#{bodyBean.items}" var="body" border="1" cellpadding="10" cellspacing="1">
                <f:facet name="header">
                    <h:commandButton value="Добавить" action="#{bodyBean.addItem()}"/>
                    <h:commandButton value="Обновить" action="#{bodyBean.refresh()}"/>
                    <h:outputText value="Таблица кузовов"/>
                </f:facet>        
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="ID"/>
                    </f:facet>
                    <h:outputText value="#{body.id}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="Тип кузова"/>
                    </f:facet>
                    <h:outputText value="#{body.bodyType.name}"/>
                </h:column>                
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="Цвет"/>
                    </f:facet>
                    <h:outputText value="#{body.color.name}"/>
                </h:column>                
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="Дверей (шт.)"/>
                    </f:facet>
                    <h:outputText value="#{body.doorCount}"/>
                </h:column>                
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="VIN"/>
                    </f:facet>
                    <h:outputText value="#{body.vin}"/>
                </h:column>                
                <h:column>
                    <h:commandButton value="Редактировать" action="#{bodyBean.editItem(body)}"/> 
                </h:column>
                <h:column>
                    <h:commandButton value="Удалить" action="#{bodyBean.deleteItem(body)}"/>
                </h:column>
                <f:facet name="footer">
                    <h:commandButton value="Закрыть" action="index"/>
                </f:facet>                        
            </h:dataTable>
        </h:form>
    </h:body>
</html>

auto/auto-web/src/main/webapp/bodyTypeCard.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Карточка тип кузова</title>
    </h:head>
    <h:body>
        <h:form>
            <h:panelGrid columns="2" border="1" cellpadding="10" cellspacing="1">
                <f:facet name="header">
                    <h:outputText value="Карточка кузов"/>
                </f:facet>                
                <h:outputText value="№"/>
                <h:outputText value="#{bodyTypeBean.selectedItem.id}"/>
                <h:outputText value="Название"/>
                <h:inputText value="#{bodyTypeBean.selectedItem.name}"/>
                <f:facet name="footer">
                    <h:commandButton value="Сохранить" action="#{bodyTypeBean.saveItem()}"/>
                    <h:commandButton value="Закрыть" action="#{bodyTypeBean.cancelItem()}"/>
                </f:facet>                            
            </h:panelGrid>            
        </h:form>
    </h:body>
</html>

auto/auto-web/src/main/webapp/bodyTypeTable.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Таблица типов кузова</title>
    </h:head>
    <h:body>        
        <h:form>            
            <h:dataTable value="#{bodyTypeBean.items}" var="bodyType" border="1" cellpadding="10" cellspacing="1">
                <f:facet name="header">
                    <h:commandButton value="Добавить" action="#{bodyTypeBean.addItem()}"/>
                    <h:commandButton value="Обновить" action="#{bodyTypeBean.refresh()}"/>
                    <h:outputText value="Таблица типов кузова"/>
                </f:facet>        
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="ID"/>
                    </f:facet>
                    <h:outputText value="#{bodyType.id}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">
                        <h:outputText value="Имя"/>
                    </f:facet>
                    <h:outputText value="#{bodyType.name}"/>
                </h:column>                
                <h:column>
                    <h:commandButton value="Редактировать" action="#{bodyTypeBean.editItem(bodyType)}"/> 
                </h:column>
                <h:column>
                    <h:commandButton value="Удалить" action="#{bodyTypeBean.deleteItem(bodyType)}"/>
                </h:column>
                <f:facet name="footer">
                    <h:commandButton value="Закрыть" action="index"/>
                </f:facet>                                        
            </h:dataTable>
        </h:form>
    </h:body>
</html>

auto/auto-web/src/main/webapp/colorCard.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Карточка цвета</title>
    </h:head>
    <h:body>
        <h:form>
            <h:panelGrid columns="2" border="1" cellpadding="10" cellspacing="1">
                <f:facet name="header">
                    <h:outputText value="Карточка цвета"/>
                </f:facet>                
                <h:outputText value="№"/>
                <h:outputText value="#{colorBean.selectedItem.id}"/>
                <h:outputText value="Название"/>            
                <h:inputText value="#{colorBean.selectedItem.name}"/>
                <f:facet name="footer">
                    <h:commandButton value="Сохранить" action="#{colorBean.saveItem()}"/>
                    <h:commandButton value="Закрыть" action="#{colorBean.cancelItem()}"/>
                </f:facet>                            
            </h:panelGrid>            
        </h:form>
    </h:body>
</html>

auto/auto-web/src/main/webapp/engineCard.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Карточка двигатель</title>
    </h:head>
    <h:body>
        <h:form>
            <h:panelGrid columns="2" border="1" cellpadding="10" cellspacing="1">
                <f:facet name="header">
                    <h:outputText value="Карточка двигателя"/>
                </f:facet>                
                <h:outputText value="№"/>
                <h:outputText value="#{engineBean.selectedItem.id}"/>
                <h:outputText value="Тип двигателя"/>            
                <h:selectOneMenu value="#{engineBean.selectedEngineType}">
                    <f:selectItems value="#{engineTypeBean.engineTypes}"/>                
                </h:selectOneMenu>          
                <h:outputText value="Объем (см3)"/>            
                <h:inputText value="#{engineBean.selectedItem.volume}"/>
                <h:outputText value="Мощность (КВт)"/>            
                <h:inputText value="#{engineBean.selectedItem.power}"/>
                <h:outputText value="SN"/>            
                <h:inputText value="#{engineBean.selectedItem.sn}"/>
                <f:facet name="footer">
                    <h:commandButton value="Сохранить" action="#{engineBean.saveItem()}"/>
                    <h:commandButton value="Закрыть" action="#{engineBean.cancelItem()}"/>
                </f:facet>                
            </h:panelGrid>                
        </h:form>
    </h:body>
</html>

auto/auto-web/src/main/webapp/transmissionCard.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>Карточка трансмиссия</title>
    </h:head>
    <h:body>        
        <h:form>
            <h:panelGrid columns="2" border="1" cellpadding="10" cellspacing="1">
                <f:facet name="header">
                    <h:outputText value="Карточка трансмиссия"/>
                </f:facet>                
                <h:outputText value="№"/>
                <h:outputText value="#{transmissionBean.selectedItem.id}"/>
                <h:outputText value="SN"/>
                <h:inputText value="#{transmissionBean.selectedItem.sn}"/>
                <h:outputText value="Тип трансмиссии"/>
                <h:selectOneMenu value="#{transmissionBean.selectedTransmissionType}">
                    <f:selectItems value="#{transmissionTypeBean.transmissionTypes}"/>                
                </h:selectOneMenu>
                <f:facet name="footer">
                    <h:commandButton value="Сохранить" action="#{transmissionBean.saveItem()}"/>
                    <h:commandButton value="Закрыть" action="#{transmissionBean.cancelItem()}"/>
                </f:facet>                
            </h:panelGrid>
        </h:form>
    </h:body>
</html>